### ISSUE TITLE
shouldDisableDate does not work when using "Year picker"

### ISSUE THREAD

**Issue by dmdionisio** [mui-org/material-ui-pickers#1002]
When using DatePicker to select an year `shouldDisableDate` does not work.

```
<DatePicker
    views={['year']}
    shouldDisableDate={day => true}
```
still displays all years from 1900 to 2100

**Comment by dmtrKovalenko** [comment]
If you want to disable years you must use minDate or maxDate.

**Comment by dmtrKovalenko** [comment]
Because of performance issues. If we will run 365 times the function for each day :(

**Comment by dmdionisio** [comment]
> If you want to disable years you must use minDate or maxDate.

But this way is not possible to have as options [2000, 2005, 2010, 2015] for example.

**Comment by dmdionisio** [comment]
> Because of performance issues. If we will run 365 times the function for each day :(

What about passing as prop the valid dates instead?

**Comment by oliviertassinari** [comment]
Please provide a full reproduction test case with the latest version (v4.0.0-alpha.5 as we are writing). This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/cool-cherry-v3cbt) _may_ be a good starting point. Thank you!

**Comment by dmtrKovalenko** [comment]
I understand the issue. We need to consider a proper approach `shouldDisableDate` can disable any day, but year and month view will not reflect the disabled state.

**Comment by dmtrKovalenko** [comment]
Actually the main reason for not adding this behavior is performance. Because in order to make sure that we need to disable the year we need to call this function 365 times. This is too slow, we can see it on our current behavior for an autoselecting closest enabled date. So in order to show the list of 100 years in year selection, we need to run this function 365 000 times. 

I can propose the following algorithm to speedup the checking
1) Break the year in 2 parts
2) Check the first and last day of each part
3) If all days disabled – break each of part in 2 parts
4) Go to 2 

This can help to speedup checking years, but will not help if there is only one day in year enabled. We need to make possible to choose this year 🤯  

Only one thing I can imagine is providing `shouldDisableYear` function, but another problem that it will be possible to implement it differently for `shouldDisableDay` and it will be even weirder.

**Comment by oliviertassinari** [comment]
+1 for a `shouldDisableYear` prop. I think that disable day and year will cover different use cases.

**Comment by ieltxualganaras** [comment]
What about disabling months within a year for year-month pickers?

**Comment by dmtrKovalenko** [comment]
The same. We'll need also `shouldDisableMonth`

**Comment by oliviertassinari** [comment]
@dmtrKovalenko Maybe we should have an API like this?

```tsx
shouldDisableDate?: (date, range?: 'day' | 'month' | 'quarter' | 'year') => Boolean;
```

**Comment by dmtrKovalenko** [comment]
I think it will only make it easier to lose that you will disable a whole year by disabling just the first day. 
Moreover, it will introduce a weird and easy-to-miss breaking change.

**Comment by JordanWinslow** [comment]
@dmtrKovalenko I'm using @material-ui/pickers 3.2.10 and I do not see shouldDisableYear or shouldDisableMonth in my DatePickerProps definition. Am I doing something wrong or perhaps have the TS definitions not been updated?
