### ISSUE TITLE
getYearRange return wrong years after 1969

### ISSUE THREAD

**Issue by MatteoGioioso** [mui-org/material-ui-pickers#1106]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.0.0     |
| material-ui          |    4.1.0     |
| React                |     16.8    |
| Browser              |         |
| Peer library         |    moment 2.24     |  |

## Steps to reproduce
I would like to display a custom array of years, starting from the current year till 1900 in reverse order.
I am trying to override `getYearRange`, but at after 1969 I get 2068 instead of 1968

## Expected behavior
It should display years normally

## Actual behavior
after `1969` it displays `2068`

## Live example

https://codesandbox.io/s/momentutils-year-range-bq7lq

**Comment by dmtrKovalenko** [comment]
Here you go https://codesandbox.io/s/momentutils-year-range-13emx

**Comment by MatteoGioioso** [comment]
But why that behavior? And why I cannot pass a simple array of years?

**Comment by dmtrKovalenko** [comment]
Because you are passing 2067 and 2068 year.
![image](https://user-images.githubusercontent.com/16926049/59259919-4fbd1500-8c43-11e9-8ebb-54c972f3a4dd.png)

 `LL` format is for the full date, and when it fails when you are using just year. https://codesandbox.io/s/momentutils-year-range-es7s4 here works perfectly with you code. 

But it is really awful to parse dates - much slower. Better to iterate and create new instances

**Comment by MatteoGioioso** [comment]
Ok, thanks!
