### ISSUE TITLE
Custom "onClick" for icon on KeyboardDatePicker

### ISSUE THREAD

**Issue by solenoo** [mui-org/material-ui-pickers#1119]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  v3.1.0       |
| material-ui          |   v4.1.1      |
| React                |   v16.8.6      |
| Browser              |   Chrome:  v74.0.3729.169     |
| Peer library         |        moment  |

## Steps to reproduce

1. Use **KeyboardDatePicker**
2. Set **keyboardIcon** prop to be different icon when there is a value
3. Set **KeyboardButtonProps** to pass custom **onClick** when there is a value

## Expected behavior

I'm expecting to be able to set a custom **onClick** on the icon button.

## Actual behavior

The icon changes, but the **onClick** is the default one and opens the **Calendar**

## Live example

[demo](https://codesandbox.io/s/material-ui-pickers-usage-demo-rigtp)

**Comment by dmtrKovalenko** [comment]
Why do you need custom onClick?

**Comment by solenoo** [comment]
@dmtrKovalenko as the example shows I would like to be able to **clear** outside the **Calendar**

**Comment by dmtrKovalenko** [comment]
This is very weird workaround to clear button, we will not approve it. 
Please use smth like that https://codesandbox.io/s/material-ui-pickers-usage-demo-2vnf5

**Comment by alexandra-c** [comment]
> This is very weird workaround to clear button, we will not approve it.
> Please use smth like that https://codesandbox.io/s/material-ui-pickers-usage-demo-2vnf5

But this is not a good solution either, when moving the Open Button to the left, the label will always be "stuck" to the top of the component as if there is something selected even though the value was cleared. 
![image](https://user-images.githubusercontent.com/46926675/87763501-8fc6d200-c81d-11ea-920e-2110b464d305.png)
This does not look too good, the label should be inside of the TextField component like this: 
![image](https://user-images.githubusercontent.com/46926675/87763810-0e237400-c81e-11ea-94a6-4d7a3e7b9a57.png)
But we cant do this because of this current issue.

Thanks
Waiting for a better fix for this.
