### ISSUE TITLE
Picker clear causes re-rendering loop.

### ISSUE THREAD

**Issue by nnaku** [mui-org/material-ui-pickers#1126]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.1.1     |
| material-ui          |    4.1.1     |
| React                |    16.8.6     |
| Browser              |  Chrome 75.0.3770.90 (Official Build) (64-bit)   |
| Peer library         |  date-fns 2.0.0-alpha.34 |
| Peer library         |  dayjs 1.8.14 | 
| Peer library         | luxon 1.16.0 | 
| Peer library         |  moment 2.24.0|

## Steps to reproduce

Use clearable picker CLEAR button to set a value to `null`

## Expected behavior
`value === null` and that's it.

## Actual behavior
Clear causes some kind of  slow "re-rendering" loop and keeps updateing component. 

## Live example
[sandbox](https://codesandbox.io/s/priceless-feynman-v0ls9)
enable "Highlight Updates" on react dev tools and test [here](https://v0ls9.codesandbox.io/)

![not so funny gif](https://media.giphy.com/media/l2uxCObPQXUUCoOo9c/giphy.gif)

**Comment by Kimahriman** [comment]
Also getting constant rerenders, but nothing to do with clearing. Just rendering a DatePicker with a value and onChange gives me constant rerenders.

**Comment by Kimahriman** [comment]
So it's an issue with having a blank date. [useDateValues](https://github.com/mui-org/material-ui-pickers/blob/next/lib/src/_shared/hooks/usePickerState.ts#L23) will always return a new date with the current time when `value` is falsy, meaning the check [here](https://github.com/mui-org/material-ui-pickers/blob/next/lib/src/_shared/hooks/usePickerState.ts#L41) will always be true, thus continually calling `setPickerDate` and rerendering. Not sure what the exact expected behavior is so I don't know the exact fix.

**Comment by nnaku** [comment]
> Not sure what the exact expected behavior is so I don't know the exact fix.

@dmtrKovalenko any advices about this?

**Comment by jhrinoa** [comment]
I also noticed this issue.
I created a codesandbox example to describe this issue.

https://codesandbox.io/s/jolly-river-ob9zo

Open Chrome's task manager. Notice the CPU goes 100% after you clear the field by clicking "clear" button.
