### ISSUE TITLE
Allow users to enter timestamps instead of datetime (or break picker out from textfield to allow custom logic on textfield)

### ISSUE THREAD

**Issue by Exitialis1** [mui-org/material-ui-pickers#1167]
![I just want to use timestamps](https://i.imgflip.com/3573eg.jpg)

**Is your feature request related to a problem? Please describe.**
I would like to allow users to enter date times as time stamp format because that is how I am storing them in the database and how the API handles date time.

**Describe the solution you'd like**
Ideally the text field would be able to identify unix time stamps on input instead of trying to parse them as a date time value.

**Describe alternatives you've considered**
A good (perhaps better) alternative would be to break out the picker from the textfield so that we could implement our own text field with custom logic while still using the awesome picker.

**Comment by barbalex** [comment]
> A good (perhaps better) alternative would be to break out the picker from the textfield so that we could implement our own text field with custom logic while still using the awesome picker

+1

I want my users te be able to type `1`. Then my code will set the first of this month of this year.
If they type `1.1` my code will set the first day of the first month of this year.
if they type `01.01` that will work too.
And so on.

And if someone wants to use the picker there is a symbol to choose a date via the picker.

This was possible with version 2. Seems no more with v3 :-(

**Comment by barbalex** [comment]
Maybe https://github.com/mui-org/material-ui-pickers/issues/1066 could help to achieve this too.

**Comment by dmtrKovalenko** [comment]
Actually there is a feature for that already waiting to be releases

**Comment by dmtrKovalenko** [comment]
Released support of `variant=static` so you are now able to make custom textfield

**Comment by barbalex** [comment]
Actually I realized that I do not need to use custom field to enable lazy input of dates directly in the field. What is needed is:
- `format="D.M.YYYY"` (single D and M enables not having to type leading zeroes)
- remove all the masking of the input numbers in the onBlur handler
- create the date using `new Date(moment(value, 'DD.MM.YYYY').format('YYYY-MM-DD'))` to add missing parts of the date

For a complete example see here: https://github.com/barbalex/vermehrung/blob/master/src/components/shared/DateFieldWithPicker.js

**Comment by dmtrKovalenko** [comment]
You can replace mask with a simple regex /._/

**Comment by barbalex** [comment]
Somehow I managed to miss that a user cannot enter a double digit day or month this way - so ignore my above comment :-(

**Comment by dmtrKovalenko** [comment]
Why not to make default mask? That is simple and clear?

**Comment by barbalex** [comment]
@dmtrKovalenko what do you mean by "default mask"?

If you mean a format like "DD.MM.YYYY", the answer is:

Yeah, it is simple and clear. But the users of some of my apps primarily have to enter dates close to now().

Example: a business app. Secretaries enter the date, when something new happened. It usually has just happened.

So quite often all they need to enter is the day, because they enter the date during the same month and year as the date they want to enter.

So if all they have to type is `5` to enter `05.09.2019` secretaries are extremely fast.
But if they have to type `05.09.2009` that is 10 times more, thus 10 times less efficient.
Also using a mouse to open a calendar and choose a date is multiple times slower than simply typing one or two numbers. But there are also non-secretaries working with this app and they like to open the calendar.

**Comment by Exitialis1** [comment]
Static variant is perfect, thank you :+1:

**Comment by barbalex** [comment]
yeah, I will be using it too
