### ISSUE TITLE
I pass UTC date object but DateTimePicker show local time.

### ISSUE THREAD

**Issue by Ch-Valentine** [mui-org/material-ui-pickers#1332]
I'm using date-io/luxor as provider's utils. Help me please to fix it

**Comment by ericrobinsondev** [comment]
The issue is that this line:
https://github.com/mui-org/material-ui-pickers/blob/0fd30945ef8caf1e877515dd8bfb2d05985b2d2c/lib/src/_shared/hooks/usePickerState.ts#L18 will return a native JS object in the browser's local timezone, no matter what timezone you pass it (at least for date-fns that I am using)

**Comment by dmtrKovalenko** [comment]
Please provide more info to reproduce.
