### ISSUE TITLE
minDate and maxDate isn't working with TimePicker

### ISSUE THREAD

**Issue by robertherber** [mui-org/material-ui-pickers#1369]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.5     |
| material-ui          |     4.4.1    |
| React                |    16.9     |
| Browser              |     Chrome    |
| Peer library         |    dayjs@1.8.16, @date-io/dayjs@1.3.11     |  |

## Steps to reproduce

1. Set minDate and/or maxDate on a <TimePicker />.

## Expected behavior

I'd expect the times outside the range between the minDate/maxDate to be unselectable.

## Actual behavior

It doesn't have any effect - all 24 hours are still selectable.

## Live example

https://codesandbox.io/s/material-ui-pickers-usage-demo-g6zxl

**Comment by dmtrKovalenko** [comment]
Added `minTime` and `maxTime` in v4

**Comment by zsinryu** [comment]
Can we use minDate and maxDate instead of adding new attriubte?

**Comment by ajmueller** [comment]
@dmtrKovalenko I don't yet see those props in the docs for v4 (as of this writing the docs are v4.0.0-alpha.3).  Have they not been added yet?

I also agree with @zsinryu that `minDate` and `maxDate` incorporating time is necessary in some cases, particularly when selecting two interconnected dates and times across multiple days.  For instance, if you're using two date and time pickers to create an event, you'd likely want to use the entire date and time value from the start date and time as the end date and time's `minDate`.  Let's say you have an event that will run from March 18 at 8pm until March 19 at 1am.  If you only have a `minTime` and `maxTime` props, your end date selection would be limited to a `minTime` of 8pm because that's when your event starts.  That would not work since your event needs to end at 1am; my assumption here is you would not be allowed to select 1am since it's before 8pm.  Is that the case?

**Comment by tamaccount** [comment]
> Added `minTime` and `maxTime` in v4

To clarify/be sure, in the latest stable release, v3.2.9, there is no way to set a max or min for TimePicker at all?
I can't get `minTime`, `maxTime`, `minDate`, or `maxDate` to work.  Any work arounds?

Thanks.

**Comment by oliviertassinari** [comment]
@tamaccount We have stopped support on v3. Did you try with v4-alpha?

**Comment by tamaccount** [comment]
@oliviertassinari 

Thanks for responding.  I did not realize that v3 was no longer supported; I was using that version because it is default version I saw docs for at https://material-ui-pickers.dev/

I can try using v4-alpha now. What exact version of the alpha do you think is the most stable/the one that I should use? Thanks.

**Comment by oliviertassinari** [comment]
@tamaccount We still have a lot of breaking changes planned on the date picker, the main concern you should have is around handling these BCs.
