### ISSUE TITLE
No way to set DatePicker placeholder/label color

### ISSUE THREAD

**Issue by developdeez** [mui-org/material-ui-pickers#1418]
Have tried many of the stylings mentioned here and there doesnt seem to be a way to set placeholder to a color.

**Comment by dmtrKovalenko** [comment]
The same way as material ui TextField. `className` and `classes` props will be applied to the text field

**Comment by developdeez** [comment]
Could you be more specific? I dont see anything on the docs even for Textfiled for color of placeholder

**Comment by dmtrKovalenko** [comment]
https://material-ui.com/components/text-fields/#customized-inputs

**Comment by webbbret** [comment]
Just failed a build because KeyboardTimePicker didnt have color defined... Why dont you guys make these defaults? 

`<KeyboardTimePicker
                  ref={null}
                  style={undefined}
                  color={undefined}
                  className={undefined}
                  onFocus={undefined}
                  onBlur={undefined}
                  innerRef={undefined}
                  rows={undefined}
                  rowsMax={undefined}
                  margin="normal"
                  id="time-picker"
                  label="RTD Time"
                  value={this.props.fpRTDTime}
                  onChange={this.props.handleRTDTimeChange}
                  KeyboardButtonProps={{
                    'aria-label': 'change time'
                  }}
                />`

I should not have to have all of these contained/defined in the element. The element should only care about the attributes I want to have customized or that are required. Why is color required? Failing like this makes me not want to use your widget. Thanks for considering.

**Comment by dmtrKovalenko** [comment]
You don’t need all these nulls and undefined if I understand right. 
If you doubt create a codesandbox

**Comment by developdeez** [comment]
So there is an example of setting the placeholder text color? Not the text color. Just the placeholder since thats usually a different color.

**Comment by dmtrKovalenko** [comment]
Please read the documentation link I sent.

**Comment by developdeez** [comment]
But I did... Explain it like I'm 5 please.
I dont even see any examples of what I mentioned on that page.
Let me clarify, Im not talking about the text color. Just placeholder. The text that usually getting overwritten. Not the type and it floats to the top type of placeholder.

**Comment by developdeez** [comment]
Expected
![image](https://user-images.githubusercontent.com/13059525/71506951-dab4d400-2850-11ea-8c98-87e51e258d56.png)
![image](https://user-images.githubusercontent.com/13059525/71506965-e2747880-2850-11ea-8c13-63b716f9bca9.png)
Actual
![image](https://user-images.githubusercontent.com/13059525/71507020-10f25380-2851-11ea-9b3a-5d5a56eb5a11.png)

![image](https://user-images.githubusercontent.com/13059525/71507034-1b145200-2851-11ea-9ffc-2ad94c589c0d.png)

**Comment by oliviertassinari** [comment]
👋 Thanks for using Material-UI!

We use GitHub issues exclusively as a bug and feature requests tracker, however,
this issue appears to be a support request.

For support, please check out https://material-ui.com/getting-started/support/. Thanks!

If you have a question on StackOverflow, you are welcome to link to it here, it might help others.
If your issue is subsequently confirmed as a bug,  and the report follows the issue template, it can be reopened.

**Comment by developdeez** [comment]
@oliviertassinari How is that support request?
Simply providing a link that doesnt solve the issue isn't helpful, @dmtrKovalenko. But thanks for the attempt.
