### ISSUE TITLE
[DatePicker] ability to change month programmatically

### ISSUE THREAD

**Issue by AbdullahElrubi** [mui-org/material-ui-pickers#1431]
**Is your feature request related to a problem? Please describe.**
I've a date range selector with two DatePickers and I wanted to change months on each Calendar when I slide the other one.

**Describe the solution you'd like**
If I change Month (forward/backward) on one picker, it should update the other one programmatically or I should have a prop that I can access the `currentMonth` that is in the `CalendarState`

**Comment by AbdullahElrubi** [comment]
@dmtrKovalenko @oliviertassinari  is there anyway I can do this ?

**Comment by oliviertassinari** [comment]
@AbdallahElroby I'm not aware it's possible to fully control the displayed month. I'm not even sure it's something we want to support in the future. The best workaround I'm aware of is to set an `initialFocusedDate` prop and a `key` with it.

@dmtrKovalenko In https://github.com/mui-org/material-ui-pickers/issues/1293#issuecomment-538374383 I was proposing a `initialHighlight` prop for the same problem.
But I suspect that we should rename it `defaultHighlight` because "default" refers to an uncontrolled behavior and it avoids the usage of "focused" that refers to a DOM focused element. However, we likely want it to have the accessible focus (!== DOM focus). I don't know what a good suffix would be 🤔 but I'm definitely in favor of "default" rather than "initial".

**Comment by vilbergs** [comment]
I see this is still open. This still seems like a reasonable thing to be able to do. We are using material-ui-pickers to build a period picker (2 calendars side by side), and being able to programatically set the months would help us sync the calendars better.

**Comment by sopranolinist** [comment]
I'm also looking for this functionality. Any idea what a good workaround would be? To be specific, what I'm looking for is that, after the user chooses a date in the first picker, when they go to open the second picker it defaults to display the month corresponding to the date chosen in the first picker even though its own value is still blank.

**Comment by oliviertassinari** [comment]
@sopranolinist Thanks for sharing your use case. While your problem focuses on the day picker, it sounds like we would have to solve the exact same issue with a [week, month, quarter or year pickers](https://ant.design/components/date-picker/#components-date-picker-demo-basic). I think that we can design a solution that covers them all. 

@dmtrKovalenko What if we would remove the `defaultHighlight` and `onMonthChange` prop. Instead, we could have a *displayed date* state, that could be controlled or uncontrolled? It would solve the same problem as:

- http://react-day-picker.js.org/api/DayPicker#initialMonth (uncontrolled)
- http://react-day-picker.js.org/api/DayPicker#month (controlled)
- http://react-day-picker.js.org/api/DayPicker#onMonthChange

but also covers the other ranges: year, quarter.

**Comment by oliviertassinari** [comment]
I'm closing for the "displayedValue" state proposal of https://github.com/mui-org/material-ui/issues/24150
