### ISSUE TITLE
onError is called every time

### ISSUE THREAD

**Issue by DanilloCorvalan** [mui-org/material-ui-pickers#1451]
https://github.com/mui-org/material-ui-pickers/blob/689d7d33bdac5e649d4e5c6ca37f9f523c80b8cf/lib/src/_shared/hooks/usePickerState.ts#L94-L98

Shouldn't it also consider the `validationError` to be set before calling it? this `useEffect` will trigger when the value changes

https://codesandbox.io/s/nifty-hofstadter-mk285?fontsize=14&hidenavigation=1&theme=dark

**Comment by dmtrKovalenko** [comment]
Yeah, we are dispatching onError with `undefined` to make sure it cleared. 
Just check if `validateionError !== currentValidationError` by yourself

**Comment by SweVictor** [comment]
I ran into this as well from a different angle. We add server validation errors from formik using formik.setFieldError("fieldName", serverError)

These errors quickly gets reset by pickers since they seem to call onError quite often. We worked around it by having a cache of last error and last value - if value doesn't change we don't clear the error.

Seems a bit silly though, is there a better way? Could MUI pickers possibly stop clearing errors unless something actually changed?

**Comment by dmtrKovalenko** [comment]
@SweVictor Try v4 (https://next.material-ui-pickers.dev/guides/forms).
We reworked validation from scratch to be more useful with formik and other form helpers.

**Comment by SweVictor** [comment]
@dmtrKovalenko Oh, nice, and thanks for the quick reply!

I'll absolutely try that out. Alpha seems to signify it's maybe not ready for production use yet? Either way, hopefully a RC will soon be here.

Thanks either way and great work on a nice library!
