### ISSUE TITLE
Keyboard usability with dayjs or luxon

### ISSUE THREAD

**Issue by radhasatam** [mui-org/material-ui-pickers#1478]
Keyboard usability when using material-ui/pickers with dayjs or luxon as the date library is not great. When trying to modify the existing date, on key press, the input focus goes to the end.

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.10     |
| material-ui          |    (core) 4.9.0     |
| React                |    16.12.0     |
| Browser              |    Chrome (79.0.3) / Firefox (72.0.2)   |
| Peer library         |   dayjs (1.8.19)  |
| date-io/dayjs      |   1.3.13    |
## Steps to reproduce

Create a keyboard date time picker using dayjs / luxon as the utils
```
<MuiPickersUtilsProvider utils={DayJsUtils}>
  <KeyboardDateTimePicker
        id="nextDate"
        variant="inline"
        label="Next Date"
        value={dt}
        onChange={setDt}
        format="YYYY/MM/DD HH:mm"
        fullWidth
   />
</MuiPickersUtilsProvider>
```

## Expected behavior

This works fine with date-fns or moment.
![Material UI Pickers with Date Fns](https://media.giphy.com/media/UV4956G2XzzfH1h2LT/giphy.gif)
Sandbox:
https://codesandbox.io/s/datefns-material-ui-pickers-0y74d

## Actual behavior

![Material UI Pickers with DayJs](https://media.giphy.com/media/lTj3cUHjBm3Wc0eTSP/giphy.gif)

## Live example

With dayjs:
https://codesandbox.io/s/dayjs-material-ui-pickers-c6wcy

**Comment by IAmMarcellus** [comment]
I have a similar problem using KeyboardTimePicker with Luxon. The entire field is cleared on keypress and an 'Invalid Time Format' message is shown. Also, the input loses focus. This happens if any key is hit, not just backspace, and even if the format should be valid (e.g. the picker is set to "1:00 AM" and I try to add another '1' to the beginning to make it "11:00 AM").

Furthermore, if I click to refocus after it's been cleared and try to type, several issues occur: I can only type 1 digit, my onChange function is never called, and I get a very strange error/stack trace:
![material-UI-Picker Error](https://user-images.githubusercontent.com/26859964/73515385-be113c00-43ba-11ea-9077-c9397209f9ff.PNG)
However, using the picker instead of the keyboard works perfectly.

Also, if I try to add a mask it doesn't show.

To make things even stranger, I have 4 other pickers in the same component that are built the same way, but they work pretty much as expected. The only problem with them is that I also can't type more than 1 digit if I clear the field on purpose.

The only remedy I've found is to just switch to TimePicker and get rid of keyboard input altogether.

I'm using material-ui/pickers 3.2.10, material-ui/core: 4.9.0, date-io/luxon: 1.3.11, luxon: 1.21.2, and react 16.8.6. And my browser is chrome.

**Comment by dmtrKovalenko** [comment]
This is fixed in v4
