### ISSUE TITLE
Error compiling with CRA and 4.x

### ISSUE THREAD

**Issue by georgiosd** [mui-org/material-ui-pickers#1560]
![GIF](https://i.giphy.com/media/xT0xeuOy2Fcl9vDGiA/giphy.webp)

## Environment

```
    "@date-io/date-fns": "^2.4.0",
    "@material-ui/core": "^4.9.5",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/pickers": "^4.0.0-alpha.3",
    "@material-ui/styles": "^4.9.0",
```

## Error

```
./node_modules/@material-ui/pickers/Picker-695cec6b.js
Attempted import error: 'fade' is not exported from '@material-ui/core/styles'.
```
Any ideas?

**Comment by oliviertassinari** [comment]
Do you have a reproduction?

**Comment by georgiosd** [comment]
@oliviertassinari I understand that it's inconvenient for you to not have a ready reproduction issue in order to investigate the issue but we have to get the release out so we just opted to keep the packages back. 

If I'm the only one with the issue let's just mark it as a random fault somewhere

**Comment by oliviertassinari** [comment]
The issue has been closed because it does not conform to our issue requirements. 
Please provide a full reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/github/mui-org/material-ui/tree/master/examples/create-react-app-with-typescript) _may_ be a good starting point. Thank you!
