### ISSUE TITLE
Can we make it possible to select year in DateRangePicker

### ISSUE THREAD

**Issue by IgorTurko** [mui-org/material-ui-pickers#1769]
Hi guys,

I am start using DateRangePicker and its great. Thanks a lot for this.
I wanted to ask can we add `year` selector to the top. The same like in `DatePicker`.
![image](https://user-images.githubusercontent.com/4738307/81808967-3b575b80-9529-11ea-94e2-629c308b6c83.png)

For example sometimes I have quite long ranges and its annoying to click `<<back` 30 times.
So what I would suggest is to add year somewhere here:
![image](https://user-images.githubusercontent.com/4738307/81809232-b02a9580-9529-11ea-9cf5-465261258fc6.png)

Or maybe its a workaround with `renderInput` props?

Br, Igor

**Comment by dmtrKovalenko** [comment]
@oliviertassinari what do you think? As for me, I think that the implementation of date range picker with year selection requires too many efforts. 

Nobody of Airbnb, booking.com, or google flights have year selection for range. But I suppose its because of business value (you're probably not looking for booking flight for 2030). But probably it can be a real case... e.g. in analytics 

@IgorTurko why do you need it?

**Comment by IgorTurko** [comment]
I have some statistics from the year 2018 lets say. And that means I need to select this date twice for the start and for the end.

**Comment by oliviertassinari** [comment]
@dmtrKovalenko agree, I don't think that the date range picker should support it. Even the existing paid UI libraries don't. Right now, end-users can work around the issue with the textbox.

Also, the usage of two date pickers could be a good tradeoff.

**Comment by oliviertassinari** [comment]
I have added the `waiting for users upvotes` tag. I'm closing the issue as we are not sure people are looking for such. So please upvote this issue if you are. We will prioritize our effort based on the number of upvotes.

**Comment by oliviertassinari** [comment]
The effort on this moved to https://github.com/mui/mui-x/issues/4546.
