### ISSUE TITLE
Last year is not clickable when use minDate and maxDate

### ISSUE THREAD

**Issue by DharmedraKumar** [mui-org/material-ui-pickers#1774]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |     4.0.0-alpha.7    |
| material-ui          |    4.9.10     |
| TypeScript           |         |
| React                |     16.13.1    |
| Browser              |         |
| Peer library         |    date-fns     |  |

## Steps to reproduce

Same code as mentioned in https://v4-0-0-alpha-7.material-ui-pickers.dev/demo/datepicker
  ```
     <DesktopDatePicker
        autoOk
        label="For desktop"
        renderInput={props => <TextField {...props} />}
        minDate={new Date("2017-06-06")}
        maxDate={new Date("2100-12-31")}
        value={selectedDate}
        onChange={date => handleDateChange(date)}
      />
```

When the minDate (2017-06-06) month is not starting Month i.e Jan, then when you click last year that is 2100, is not clickable
<img width="1440" alt="Screen Shot 2020-05-15 at 2 02 14 AM" src="https://user-images.githubusercontent.com/42033860/81983095-70120280-9650-11ea-8d89-63da75849b1b.png">
## Expected behavior
If minDate does not have starting Month i.e. Jan then also last year should be clickable

## Actual behavior
Last Year 2100 is not clickable

**Can anyone provide the workaround or If possible can it be fix as hot-fix.** Thanks!

**Comment by dmtrKovalenko** [comment]
This is actually an interesting issue. We rendering this year because it fits the `minDate/maxDate` range. But it cannot be selected because `minDate` is before the current month and date (we are shifting month and date when year is selected).

I am not sure which way to fix it will be the best, for now only fixing it by highlighting it as disabled. 
![image](https://user-images.githubusercontent.com/16926049/83354867-451ff200-a364-11ea-9201-cb3ca1e7d949.png)

**Comment by oliviertassinari** [comment]
@dmtrKovalenko I have two points of interrogation, that feels weird:

- What showing a disabled year? In the current tradeoff, it seems to have no room for it. For instance, 1999 is simply not rendered. Why not removing 2010?
- Why is the year disabled? 

in the following case, we can't select a day in 2010, but there are values that are available.

```jsx
    <DatePicker
      label="Basic example"
      value={null}
      minDate={new Date('2000-01-01')}
      maxDate={new Date('2010-04-04')}
      onChange={date => handleDateChange(date)}
      renderInput={props => <TextField {...props} />}
    />
```

In the following case, we can:

```jsx
    <DatePicker
      label="Basic example"
      value={null}
      minDate={new Date('2000-01-01')}
      maxDate={new Date('2010-06-06')}
      onChange={date => handleDateChange(date)}
      renderInput={props => <TextField {...props} />}
    />
```

It looks like the current date (1st June 2020) influences if March 31th 2010 can be selected or not.

**Comment by dmtrKovalenko** [comment]
Honestly the 2010-01-01 is bad maxDate and we must use 2099-31-12 as max date by default. 

Because we can select the January first of 2010 we must render it. But for other 354 dates in year it will be disabled. Yes it is weird - it worked differently for v4 (automatically select the closest enabled date, but it was to slow.)

**Comment by oliviertassinari** [comment]
Should we introduce a new warning to avoid @DharmedraKumar open this issue in the first place?

**Comment by dmtrKovalenko** [comment]
What type of warning do you expect?

**Comment by oliviertassinari** [comment]
@dmtrKovalenko I don't know, I didn't look closely at the possible solutions available. I wanted to raise this option as an alternative that could be as good if not better. For instance, it's something we have leverage extensively on the Autocomplete, to not handle edge cases, avoid buggy user's props, etc. Looking at the codebase of the date picker, I could only count one warning: 

https://github.com/mui-org/material-ui-pickers/blob/309f4f5643d6ee5e0b0ddac1b793525474783433/lib/src/_helpers/text-field-helper.ts#L69-L71

which makes me connect on the idea that, maybe, we could benefit from more.

In https://github.com/mui-org/material-ui-pickers/issues/1774#issuecomment-636869022, I raise questions that could suggest that #1848 solves the first visible parts of the issue, not solving the root issues (but maybe it's not worth the ROI to look closer)

**Comment by dmtrKovalenko** [comment]
Let's discuss it. 

current date only influences can date be shifted to the next year or not. When we are clicking on the `2100` (when only June 1st is enabled) we cannot select `March 31th of 2100`, so the year is disabled. 

Yes, it looks like a hotfix. But it needs to be fixed on behavior level, I suppose that adding a warning is not enough. I am seeing 2 options: 
1) Do not show year completely – it is weird because we can select `January 1st` so it needs to be shown. And also it will be possible to select 2099 and navigate to January using month arrows. 
2) Probably right fix – when the current date shifted to the selected year cannot be selected – simply select January 1st of this year. 

> Looking for how this problem is solved in other datepickers.

**Comment by oliviertassinari** [comment]
@dmtrKovalenko From my perspective, the users should be able to select the year as soon as one or more days are valid for this given year, the current day should have no impact in the logic.

**Comment by dmtrKovalenko** [comment]
Yes, but which day should be selected? What if the developer will do something like 
```jsx
<DatePicker 
   maxDate={Date("2100-01-01")}
   shouldDisableDate={date => getYear(date) < 2060} 
/>
```

**Comment by oliviertassinari** [comment]
> Yes, but which day should be selected?

I would say none, why should a day be selected?

> What if the developer will do something like

I think that `shouldDisableDate` should have precedence over `maxDate`, overriding it (or as a second-best option, if the overriding isn't possible, a cumulative effect)

**Comment by dmtrKovalenko** [comment]
> I would say none, why should a day be selected?

I mean after clicking on the year, when `setYear(currentDate, newYear)` is disabled

> I think that shouldDisableDate should have precedence over maxDate, overriding it.

But we cannot run this function 200 * 365 times to understand which year is disabled

**Comment by oliviertassinari** [comment]
> I mean after clicking on the year, when setYear(currentDate, newYear) is disabled

Oh, so your question is which month should we display if the "month" view is enabled? I guess the closest to where we were before?

> But we cannot run this function 200 * 365 times to understand which year is disabled

In this case, we can either have `maxDate` and `shouldDisableDate` have a cumulative effect or implement this proposal in: https://github.com/mui-org/material-ui-pickers/issues/1002#issuecomment-612929310.

**Comment by dmtrKovalenko** [comment]
Yeah we have a special function for this case
https://github.com/mui-org/material-ui-pickers/blob/9bca9c679d7a64057772968279de360120c78b15/lib/src/_helpers/date-utils.ts#L20

But it can be also pretty slow in some cases
