### ISSUE TITLE
Guide for updating/migrating to v4

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#1822]
Hi, is there a guide for v3 -> v4, like the [updating to v3](https://material-ui-pickers.mui-org.now.sh/guides/upgrading-to-v3) guide?

**Comment by dmtrKovalenko** [comment]
We thought about that, **but** there are too many changes already, and I am working on even more. Moreover probably you are not using picker's components too often in the codebase. 

So I propose to, *for now*, just reread the documentation and think that you are migrating to the new project. A lot of base concepts were changed. 

Later on I will probably make such a guide, but won't mention all the breaking changes and renamed props (because there are too many), only describe architectural changes and "how" to update. 

Any thoughts @oliviertassinari?

**Comment by dandv** [comment]
Thanks, for me it's easy because I haven't learned too much about v3 yet, so I'll just switch the docs to v4.

**Comment by oliviertassinari** [comment]
@dmtrKovalenko I think that we could apply the same strategy as during v0 to v1. A high-level presentation: https://v1.material-ui.com/guides/migration-v0x/, something short.
