### ISSUE TITLE
helperText equivalent

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#1823]
**Is your feature request related to a problem? Please describe.**
When the date has a valid format but is invalid for other reasons, the text displayed under the TextField shows the date format in red. That doesn't help the user figure out what's wrong.

![image](https://user-images.githubusercontent.com/33569/82794445-55e1dc80-9e27-11ea-8831-da600d7e5d6b.png)

**Describe the solution you'd like**
A `helperText` attribute would enable displaying specific errors instead of the format.

**Describe alternatives you've considered**
`renderInput={props => <TextField helperText="test" {...props} />}` didn't show the helper text.

**Comment by dmtrKovalenko** [comment]
`helperText` was moved to `renderInput` 

```js
renderInput={props => <TextField {...props}  helperText={null} />}
renderInput={({ helperText, ...props }) => <TextField {...props} />}
```

**Comment by oliviertassinari** [comment]
@dandv The issue is with the order of the spreading, always spread the props **first**, as it's done in the demos: https://next.material-ui-pickers.dev/demo/datepicker#different-views.

```diff
-renderInput={props => <TextField helperText="test" {...props} />}
+renderInput={props => <TextField {...props} helperText="test" />}
```

This would have made a great StackOverflow question! I'm sure somebody else will fall into this trap, I have seen it a couple of time with the Autocomplete.
