### ISSUE TITLE
Problem importing two moment locals conflict

### ISSUE THREAD

**Issue by Angelk90** [mui-org/material-ui-pickers#1827]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.10      |
| material-ui          |   4.9.10      |
| React                |     16.13.1    |
| Peer library         |   Moment/2.24.0      |  |

## Expected behavior

In the project I'm working on, I give the user the possibility to change the language, therefore the calendar language should also change accordingly.
But it seems that importing two moment locals conflict.

So I created an example where I import both languages.
I have two MuiPickersUtilsProvider, with two different languages set.
The days of the week conflict.

As seen in the image, the set language is English, but as seen from the calendar, it is a mixture of English (month) and Italian (days).
![Schermata da 2020-05-25 12-15-09](https://user-images.githubusercontent.com/20476002/82803876-92dabd00-9e81-11ea-82eb-fec24e7de36e.png)

## Actual behavior

That according to the selected language, the local fee worked.

## Live example
@dmtrKovalenko , @oliviertassinari : [Link](https://codesandbox.io/s/material-uipickers-moment-format-l-mask-issue-dtdh1)

**Comment by dmtrKovalenko** [comment]
This is a problem of the moment, actually because of its global-oriented architecture. This is how it is possible to retrieve weekdays only from the global moment instance. It means that locale data will be used only from the global moment locale selected right now. 

https://github.com/dmtrKovalenko/-date-io/blob/ec26b62fba8bb64b412ca10b07809c5e2bc084d2/packages/moment/src/moment-utils.ts#L276

The only workaround that I am seeing is to override the `getWeekDays` method. [here docs](https://next.material-ui-pickers.dev/guides/date-io-customization#override-date-logic)
