### ISSUE TITLE
shouldDisableDate is ok, but the date can be Selected

### ISSUE THREAD

**Issue by YuZaiShui** [mui-org/material-ui-pickers#1851]
You can see what i had done.

https://theron.theronts.com:9000/api/v1/file/op-server/users/685438125505388544/uploads/ej64c6w09jmuv685gfzkefma9.mp4

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | ^3.2.10        |
| material-ui          | ^4.9.7        |
| TypeScript           | ^3.8.3        |
| React                | ^16.12.0    |
| Browser              | chrome  83.0.4103.61 |
| Peer library         |         |  |

## Steps to reproduce

1.
 
![image](https://user-images.githubusercontent.com/29266871/83604239-6ec95b00-a5a8-11ea-8252-0866cfbc5dd2.png)

2.
availableDateArr init value is [null], and i will set value when onAccept be called.
 3.
Thank you for your attention and reply.

## Expected behavior
At now, I think 6/3 should be disabled and can't be Selected auto.

## Actual behavior
The 6/3 will be Selected auto when i opened the modal.

**Comment by oliviertassinari** [comment]
The issue has been closed because it does not conform to our issue requirements. 
Please provide a minimal reproduction test case with v4.0.0-alpha.8. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/festive-golick-ej7q7?file=/src/App.jsx) _may_ be a good starting point. Thank you!
