### ISSUE TITLE
[RFC] Inline date-io inside the date picker

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-pickers#1898]
Answering #1895 made me think again of a thought I had a few months ago. date-io has been around for 2 years, with the ambition to be used outside of the use cases of Material-UI.

I think that we can take a step back and look at the potential at this market, and how it has delivered. npm lists (approximately) the most downloaded packages, `@date-io/core` is a dependency of in https://www.npmjs.com/browse/depended/@date-io/core. I couldn't find one package that has over 1k downloads/month and doesn't have `@material-ui/pickers` as a dependency.

Do you have an example package that would match these criteria? If not, I think that we could conclude that there is very limited potential for it. And think about what would it look like if date-io was merged inside the main repository too. I'm curious to see what the outcome of https://github.com/gpbl/react-day-picker/issues/980 will be.

As we plan to expand the usage of date-io to more components inside Material-UI, I start to think that hosting the source at the same place would allow us to be more efficient, shaping better API, avoiding the release synchronization pain.

**Comment by JRagone** [comment]
While I'm not a contributor to this repo, as a user of pickers I'm strongly in favor of a merge with `date-io`. I recently ran into #1440, and from the discussion in that thread, it seemed like @oliviertassinari was suggesting that there's no reason to upgrade the `date-io` version, because in all likelihood no other packages are dependent on it. If this is the case, i.e. pickers is strongly dependent on `date-io` and no other packages depend on `date-io`, then it seems merging the two would be a very logical step, as it resolves the aforementioned release synchronization pain.

**Comment by oliviertassinari** [comment]
@JRagone The root issue of #1440 was solved (in the `next` branch) by hiding the dependency to developers. It won't happen again in the future. I don't think this is an argument we should consider for a merge.

**Comment by oliviertassinari** [comment]
> pickers is strongly dependent on date-io and **no other packages** depend on date-io, then it seems merging the two would be a very logical step, as it resolves the aforementioned **release synchronization pain**.

Yes, this argument, I can get behind with 👍

**Comment by oliviertassinari** [comment]
Let's do that in v5, we need to have a close feedback loop. We can probably duplicate the source, and iterate on them once in the same repo.
