### ISSUE TITLE
KeyboardDateTimePicker compnenet : Date and Time is not editable using keyboard / number or Up /Down arrow keys.

### ISSUE THREAD

**Issue by harishmoghe** [mui-org/material-ui-pickers#2029]
- [ ] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

**Comment by oliviertassinari** [comment]
The issue has been closed because it does not conform to our issue requirements. 
Please provide a minimal reproduction test case with v4.0.0-alpha.10. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/material-ui-date-picker-ppt05) _may_ be a good starting point. Thank you!
