### ISSUE TITLE
Customization of am & pm labels 

### ISSUE THREAD

**Issue by amirqasemi74** [mui-org/material-ui-pickers#2081]
I want to change am & pm labels. is there any way?

**Comment by oliviertassinari** [comment]
👋 Thanks for using Material-UI!

We use GitHub issues exclusively as a bug and feature requests tracker, however,
this issue appears to be a support request.

For support, please check out https://material-ui.com/getting-started/support/. Thanks!

If you have a question on StackOverflow, you are welcome to link to it here, it might help others.
If your issue is subsequently confirmed as a bug,  and the report follows the issue template, it can be reopened.

**Comment by ScripterSugar** [comment]
Hi. I found your issue while searching for similar issue I faced. I found a way to customize AM/PM label by extending date-io Util class, So I'm here to share it.

```javascript
// Extend your Utils Class here (DateFNSUtils, MomentUtils, ...etc)

class ModifiedUtils extends MomentUtils {
  constructor(props) {
    super(props);
  
    this.getMeridiemText = (ampm) => {
      return ampm === 'am' ? 'YOUR_AM_STRING' : 'YOUR_PM_STRING';  // use your own AM/PM format here.
    }
  }
}
...

<MuiPickersUtilsProvider utils={ModifiedUtils}> // Give ModifiedUtils as util prop instead of origin Utils Class.
```

Hope it solved your problem!
