### ISSUE TITLE
KeyboardDateTimePicker->inputValue: Invalid date entered and then when setting value to null || undefined || '' the date is not getting cleared.

### ISSUE THREAD

**Issue by kirankumarrr** [mui-org/material-ui-pickers#2140]
bug:
KeyboardDateTimePicker->inputValue: Invalid date entered and then when setting value to null || undefined || '' the date is not getting cleared.

To Reproduce
https://codesandbox.io/s/keyboarddatepicker-datepicker-38lsy
Enter an invalid date and then click on the clear button.

**Comment by litcodeur** [comment]
Your problem seems to be in the conditions in which you set your values 

`if (dateTime && dateTime._isValid) {...}` this code block won't be executed until a user enters the entire date ex 12/12/1212 12:12 as the `dateTime._isValid` value would be true only when the entire date is present.

The solution to your problem might be to move the `dateTime._isValid` check in the next if block `if ("_d" in now && "_d" in dateTime && now._d > dateTime._d) {...}` that would mean that only when the date is valid you would be clearing it according to your validations i.e. if it is greater than current date.

**Comment by kirankumarrr** [comment]
Yea got it, Thanks Shah62
